package postgresql

import (
	"context"
	"database/sql"
	"fmt"
	"io"
	"os"
	"strings"
	"testing"

	"github.com/Releem/mysqlconfigurer/config"
	"github.com/Releem/mysqlconfigurer/models"
	logging "github.com/google/logger"
	"github.com/lib/pq"
)

func openIntegrationPostgres(t *testing.T) *sql.DB {
	t.Helper()
	dsn := os.Getenv("RELEEM_TEST_POSTGRES_DSN")
	if dsn == "" {
		t.Skip("RELEEM_TEST_POSTGRES_DSN is not set")
	}
	db, err := sql.Open("postgres", dsn)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = db.Close() })
	if err := db.Ping(); err != nil {
		t.Fatal(err)
	}
	return db
}

func integrationPostgresConfig(t *testing.T, database string) *config.Config {
	t.Helper()
	values := parseIntegrationPostgresDSN(t, os.Getenv("RELEEM_TEST_POSTGRES_DSN"))
	sslMode := values["sslmode"]
	if sslMode != "" && sslMode != "disable" && sslMode != "require" {
		t.Skipf("RELEEM_TEST_POSTGRES_DSN sslmode %q cannot be represented by the production config", sslMode)
	}
	if values["host"] == "" || values["user"] == "" {
		t.Skip("RELEEM_TEST_POSTGRES_DSN must specify host and user to exercise CollectDbSchema")
	}
	port := values["port"]
	if port == "" {
		port = "5432"
	}
	return &config.Config{
		PgHost:     values["host"],
		PgPort:     port,
		PgUser:     values["user"],
		PgPassword: values["password"],
		PgSslMode:  sslMode == "require",
	}
}

func parseIntegrationPostgresDSN(t *testing.T, dsn string) map[string]string {
	t.Helper()
	if strings.HasPrefix(dsn, "postgres://") || strings.HasPrefix(dsn, "postgresql://") {
		var err error
		dsn, err = pq.ParseURL(dsn)
		if err != nil {
			t.Fatal(err)
		}
	}

	values := make(map[string]string)
	for dsn = strings.TrimSpace(dsn); dsn != ""; dsn = strings.TrimSpace(dsn) {
		equals := strings.IndexByte(dsn, '=')
		if equals <= 0 {
			t.Fatalf("invalid RELEEM_TEST_POSTGRES_DSN option: %q", dsn)
		}
		key := dsn[:equals]
		dsn = dsn[equals+1:]
		value, rest, err := parseIntegrationPostgresDSNValue(dsn)
		if err != nil {
			t.Fatal(err)
		}
		values[key] = value
		dsn = rest
	}
	return values
}

func parseIntegrationPostgresDSNValue(input string) (string, string, error) {
	if input == "" {
		return "", "", nil
	}
	if input[0] != '\'' {
		end := strings.IndexAny(input, " \t\n")
		if end == -1 {
			return input, "", nil
		}
		return input[:end], input[end:], nil
	}

	var value strings.Builder
	for index := 1; index < len(input); index++ {
		switch input[index] {
		case '\\':
			index++
			if index == len(input) {
				return "", "", fmt.Errorf("unterminated escape sequence in PostgreSQL DSN")
			}
			value.WriteByte(input[index])
		case '\'':
			return value.String(), input[index+1:], nil
		default:
			value.WriteByte(input[index])
		}
	}
	return "", "", fmt.Errorf("unterminated quoted value in PostgreSQL DSN")
}

func TestCollectDbSchemaAgainstPostgres(t *testing.T) {
	db := openIntegrationPostgres(t)

	if _, err := db.Exec(`
		DROP SCHEMA IF EXISTS releem_schema_it CASCADE;
		CREATE SCHEMA releem_schema_it;
		CREATE TABLE releem_schema_it.orders (
			id bigint GENERATED BY DEFAULT AS IDENTITY,
			email text NOT NULL,
			status text,
			created_at timestamp
		);
		CREATE INDEX idx_orders_email_open
			ON releem_schema_it.orders USING btree ((lower(email)) DESC NULLS FIRST)
			INCLUDE (created_at)
			WHERE status = 'open';
		CREATE TABLE releem_schema_it.events (id bigint, created_at date) PARTITION BY RANGE (created_at);
		CREATE INDEX idx_events_id ON releem_schema_it.events (id);
	`); err != nil {
		t.Fatal(err)
	}
	defer db.Exec("DROP SCHEMA IF EXISTS releem_schema_it CASCADE")

	var database string
	if err := db.QueryRow("SELECT current_database()").Scan(&database); err != nil {
		t.Fatal(err)
	}
	logger := *logging.Init("postgres-schema-integration-test", false, false, io.Discard)
	defer logger.Close()
	metrics := &models.Metrics{}
	if err := CollectDbSchema(integrationPostgresConfig(t, database), logger, database, 0, metrics); err != nil {
		t.Fatal(err)
	}

	var expressionIndex, partitionedIndex models.MetricGroupValue
	for _, index := range metrics.DB.DatabaseSchema["information_schema_indexes"] {
		switch index["index_name"] {
		case "idx_orders_email_open":
			expressionIndex = index
		case "idx_events_id":
			partitionedIndex = index
		}
	}
	if expressionIndex == nil {
		t.Fatal("expression/partial index was not collected")
	}
	keys, ok := expressionIndex["keys"].([]models.MetricGroupValue)
	if !ok || len(keys) != 1 || keys[0]["expression"] == nil || keys[0]["descending"] != true || keys[0]["nulls_first"] != true {
		t.Fatalf("unexpected expression index keys: %#v", expressionIndex["keys"])
	}
	if expressionIndex["predicate"] == nil || expressionIndex["include_columns"] == nil {
		t.Fatalf("partial predicate or INCLUDE columns were lost: %#v", expressionIndex)
	}
	if partitionedIndex == nil || partitionedIndex["is_partitioned"] != true || partitionedIndex["relation_kind"] != "I" {
		t.Fatalf("partitioned index identity was not preserved: %#v", partitionedIndex)
	}
}

func TestCollectPgStatStatementsAgainstPostgres(t *testing.T) {
	db := openIntegrationPostgres(t)
	if _, err := db.Exec(`
		CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
		DROP SCHEMA IF EXISTS releem_pgss_it CASCADE;
		CREATE SCHEMA releem_pgss_it;
		CREATE TABLE releem_pgss_it.probe (id integer);
		INSERT INTO releem_pgss_it.probe VALUES (1), (2), (3);
		SELECT pg_stat_statements_reset();
	`); err != nil {
		t.Fatal(err)
	}
	defer db.Exec("DROP SCHEMA IF EXISTS releem_pgss_it CASCADE")
	for i := 0; i < 3; i++ {
		var count int
		if err := db.QueryRow("SELECT count(*) FROM releem_pgss_it.probe").Scan(&count); err != nil {
			t.Fatal(err)
		}
	}

	logger := *logging.Init("postgres-pgss-integration-test", false, false, io.Discard)
	defer logger.Close()
	capabilities, err := NewPostgresCapabilities(logger).Resolve(context.Background(), db)
	if err != nil {
		t.Fatal(err)
	}
	expectedTimingColumn := "total_exec_time"
	if capabilities.ServerVersionNum < 130000 {
		expectedTimingColumn = "total_time"
	}
	if capabilities.TimingColumn != expectedTimingColumn {
		t.Fatalf("unexpected timing column for server %d: %s", capabilities.ServerVersionNum, capabilities.TimingColumn)
	}
	rows, err := collectPostgresQueryDetails(context.Background(), db, capabilities)
	if err != nil {
		t.Fatal(err)
	}
	for _, row := range rows {
		if row.Query == "SELECT count(*) FROM releem_pgss_it.probe" {
			if row.Calls != 3 || row.Rows != 3 || row.TotalExecTimeMS < 0 || row.MeanExecTimeMS < 0 {
				t.Fatalf("unexpected PGSS payload: %#v", row)
			}
			return
		}
	}
	t.Fatalf("probe query was not found in PGSS payload: %#v", rows)
}

func TestExecuteExplainPgStatStatementsTypedLiteralsAgainstPostgres(t *testing.T) {
	db := openIntegrationPostgres(t)
	if _, err := db.Exec(`
		DROP SCHEMA IF EXISTS releem_explain_it CASCADE;
		CREATE SCHEMA releem_explain_it;
		CREATE TABLE releem_explain_it.events (
			id bigint,
			event_date date,
			created_at timestamp
		);
	`); err != nil {
		t.Fatal(err)
	}
	defer db.Exec("DROP SCHEMA IF EXISTS releem_explain_it CASCADE")

	logger := *logging.Init("postgres-explain-integration-test", false, false, io.Discard)
	defer logger.Close()
	explain, err := ExecuteExplain(
		db,
		"typed_literals",
		"SELECT id FROM releem_explain_it.events WHERE id = $1 AND created_at >= timestamp $2 AND event_date = date $3",
		true,
		logger,
	)
	if err != nil {
		t.Fatal(err)
	}
	if explain == "" {
		t.Fatal("expected PostgreSQL EXPLAIN JSON")
	}
}
